### ISSUE TITLE
ae_table_grade / noms de variables en majuscule

### ISSUE THREAD

**Issue by BaptisteArchambaud** [Oncostat/grstat#1]
Erreur dans l'appel de ae_table_grade si mon nom de variable est en majuscule.

Exemple :
ae_table_grade(df_ae=df_ae, df_enrol=df_enrol, subjid = "ENROLLID2", grade = "grade")

Error in `full_join()`:
! Join columns in `x` must be present in the data.
✖ Problem with `enrollid2`.

**Comment by DanChaltiel** [comment]
En fait le bug est même plus sévère que ça, ça ne marche que si tolower(subjid)="SUBJID".
Je corrige ça asap, en attendant il faut renommer les 2 datas d'entrée :s
