### ISSUE TITLE
assert_names_exists {df_name}

### ISSUE THREAD

**Issue by charlottebargain** [Oncostat/grstat#27]
**Describe the new feature**
Add {.} around df_name in function cli_abort

**Known workaround**
cli_abort("Columns not found in {.arg {df_name}}: {.val {a}}", class="edc_name_notfound_error")

**Comment by DanChaltiel** [comment]
Contexte: 

https://github.com/Oncostat/grstat/blob/96c36dbbf124529a7ea6934a90f0e17022489385/R/assertions.R#L47-L51

Peut-être ajouter un unit-test pour vérifier le nom ?
