### ISSUE TITLE
ae_table_grade / nb of digits in percentages

### ISSUE THREAD

**Issue by BaptisteArchambaud** [Oncostat/grstat#7]
Hi,

Could it be possible to add an option "round" or "digits" to control the number of digits displayed for percentages of events.

**Comment by DanChaltiel** [comment]
https://github.com/Oncostat/grstat/blob/d5ec96670ffa0477b08525644249d1b649d75080/R/ae_table_grade.R#L111

- [ ] Pass the ellipsis to crosstable(): `crosstable::crosstable(matches(rex), ..., )`
